/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.beastiebots.ftcScoringLite.blockParty;

import org.beastiebots.ftcScoringLite.blockParty.enums.*;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Jacob
 */
public class BlockPartyScorePanel extends javax.swing.JPanel {
    private BlockPartyScore score = new BlockPartyScore();
    /**
     * Creates new form AllianceScore
     */
    public BlockPartyScorePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        irPos = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        auto = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        auto1Pos = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        auto1Block = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        auto2Pos = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        auto2Block = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        blocks = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pendulum1 = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        pendulum2 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        pendulum3 = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        pendulum4 = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        low = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        balanced = new javax.swing.JCheckBox();
        endgame = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lift2 = new javax.swing.JCheckBox();
        lift1 = new javax.swing.JCheckBox();
        flag = new javax.swing.JComboBox();
        penalties = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        major = new javax.swing.JSpinner();
        minor = new javax.swing.JSpinner();

        irPos.setModel(new DefaultComboBoxModel(AutoBlock.valuesPendulum()));
        irPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irPosActionPerformed(evt);
            }
        });

        jLabel9.setText("IR Beacon Basket");

        auto.setBorder(javax.swing.BorderFactory.createTitledBorder("Autonomous"));

        jLabel5.setText("Block:");

        auto1Pos.setModel(new DefaultComboBoxModel(AutoPosition.values()));
        auto1Pos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auto1PosActionPerformed(evt);
            }
        });

        jLabel3.setText("Robot 1");

        auto1Block.setModel(new DefaultComboBoxModel(AutoBlock.values()));
        auto1Block.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auto1BlockActionPerformed(evt);
            }
        });

        jLabel4.setText("Position:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(auto1Pos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(auto1Block, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(auto1Pos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(auto1Block, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel6.setText("Block:");

        auto2Pos.setModel(new DefaultComboBoxModel(AutoPosition.values()));
        auto2Pos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auto2PosActionPerformed(evt);
            }
        });

        jLabel7.setText("Robot 2");

        auto2Block.setModel(new DefaultComboBoxModel(AutoBlock.values()));
        auto2Block.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auto2BlockActionPerformed(evt);
            }
        });

        jLabel8.setText("Position:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(auto2Pos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(auto2Block, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(auto2Pos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(auto2Block, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout autoLayout = new javax.swing.GroupLayout(auto);
        auto.setLayout(autoLayout);
        autoLayout.setHorizontalGroup(
            autoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autoLayout.createSequentialGroup()
                .addGroup(autoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        autoLayout.setVerticalGroup(
            autoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autoLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        blocks.setBorder(javax.swing.BorderFactory.createTitledBorder("Blocks"));

        jLabel10.setText("Pendulum Goals");

        jLabel11.setText("1:");

        pendulum1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));
        pendulum1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pendulum1StateChanged(evt);
            }
        });

        jLabel12.setText("2:");

        pendulum2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));
        pendulum2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pendulum2StateChanged(evt);
            }
        });

        jLabel13.setText("3:");

        pendulum3.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));
        pendulum3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pendulum3StateChanged(evt);
            }
        });

        jLabel14.setText("4:");

        pendulum4.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));
        pendulum4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pendulum4StateChanged(evt);
            }
        });

        jLabel15.setText("Low goal:");

        low.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));
        low.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                lowStateChanged(evt);
            }
        });

        jLabel19.setText("Balanced:");

        balanced.setMargin(new java.awt.Insets(0, 0, 0, 0));
        balanced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balancedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout blocksLayout = new javax.swing.GroupLayout(blocks);
        blocks.setLayout(blocksLayout);
        blocksLayout.setHorizontalGroup(
            blocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blocksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(blocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(blocksLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pendulum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pendulum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pendulum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pendulum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(balanced))
                    .addGroup(blocksLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(low, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        blocksLayout.setVerticalGroup(
            blocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blocksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(blocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(balanced, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(blocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(pendulum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(pendulum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(pendulum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(pendulum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(blocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(low, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        endgame.setBorder(javax.swing.BorderFactory.createTitledBorder("Endgame"));

        jLabel16.setText("Flag:");

        jLabel17.setText("Robot 1 lifted:");

        jLabel18.setText("Robot 2 lifted:");

        lift2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        lift2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lift2ActionPerformed(evt);
            }
        });

        lift1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        lift1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lift1ActionPerformed(evt);
            }
        });

        flag.setModel(new DefaultComboBoxModel(FlagHeight.values()));
        flag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flagActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout endgameLayout = new javax.swing.GroupLayout(endgame);
        endgame.setLayout(endgameLayout);
        endgameLayout.setHorizontalGroup(
            endgameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(endgameLayout.createSequentialGroup()
                .addGroup(endgameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(endgameLayout.createSequentialGroup()
                        .addGroup(endgameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(endgameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lift2)
                            .addComponent(lift1)))
                    .addGroup(endgameLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(flag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        endgameLayout.setVerticalGroup(
            endgameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(endgameLayout.createSequentialGroup()
                .addGroup(endgameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(flag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(endgameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(endgameLayout.createSequentialGroup()
                        .addComponent(lift1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lift2))
                    .addGroup(endgameLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18))))
        );

        penalties.setBorder(javax.swing.BorderFactory.createTitledBorder("Penalites"));

        jLabel23.setText("Major:");

        jLabel25.setText("Minor:");

        major.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        major.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                majorStateChanged(evt);
            }
        });

        minor.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        minor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                minorStateChanged(evt);
            }
        });

        javax.swing.GroupLayout penaltiesLayout = new javax.swing.GroupLayout(penalties);
        penalties.setLayout(penaltiesLayout);
        penaltiesLayout.setHorizontalGroup(
            penaltiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(penaltiesLayout.createSequentialGroup()
                .addGroup(penaltiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(penaltiesLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(penaltiesLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(major, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        penaltiesLayout.setVerticalGroup(
            penaltiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(penaltiesLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(penaltiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(major, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(penaltiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(minor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(auto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(blocks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(irPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 222, Short.MAX_VALUE))
                        .addComponent(endgame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(penalties, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(irPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(auto, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(blocks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(endgame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(penalties, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void irPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irPosActionPerformed
        score.setIRgoal((AutoBlock)irPos.getSelectedItem());
    }//GEN-LAST:event_irPosActionPerformed

    private void auto1PosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auto1PosActionPerformed
        score.setAutoPos1((AutoPosition)auto1Pos.getSelectedItem());
    }//GEN-LAST:event_auto1PosActionPerformed

    private void auto1BlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auto1BlockActionPerformed
        score.setAutoGoal1((AutoBlock)auto1Block.getSelectedItem());
    }//GEN-LAST:event_auto1BlockActionPerformed

    private void auto2PosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auto2PosActionPerformed
        score.setAutoPos2((AutoPosition)auto2Pos.getSelectedItem());
    }//GEN-LAST:event_auto2PosActionPerformed

    private void auto2BlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auto2BlockActionPerformed
        score.setAutoGoal2((AutoBlock)auto2Block.getSelectedItem());
    }//GEN-LAST:event_auto2BlockActionPerformed

    private void pendulum1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pendulum1StateChanged
        score.getPendulum().setBasket1((Integer)pendulum1.getValue());
    }//GEN-LAST:event_pendulum1StateChanged

    private void pendulum2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pendulum2StateChanged
        score.getPendulum().setBasket2((Integer)pendulum2.getValue());
    }//GEN-LAST:event_pendulum2StateChanged

    private void pendulum3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pendulum3StateChanged
        score.getPendulum().setBasket3((Integer)pendulum3.getValue());
    }//GEN-LAST:event_pendulum3StateChanged

    private void pendulum4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pendulum4StateChanged
        score.getPendulum().setBasket4((Integer)pendulum4.getValue());
    }//GEN-LAST:event_pendulum4StateChanged

    private void lowStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_lowStateChanged
        score.getPendulum().setLow((Integer)low.getValue());
    }//GEN-LAST:event_lowStateChanged

    private void balancedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balancedActionPerformed
        score.getPendulum().setBalanced(balanced.isSelected());
    }//GEN-LAST:event_balancedActionPerformed

    private void lift2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lift2ActionPerformed
        score.setRobot2Lifted(lift2.isSelected());
    }//GEN-LAST:event_lift2ActionPerformed

    private void lift1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lift1ActionPerformed
        score.setRobot1Lifted(lift1.isSelected());
    }//GEN-LAST:event_lift1ActionPerformed

    private void flagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flagActionPerformed
        score.setFlagState((FlagHeight)flag.getSelectedItem());
    }//GEN-LAST:event_flagActionPerformed

    private void majorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_majorStateChanged
        score.setMajorPenalties((Integer)major.getValue());
    }//GEN-LAST:event_majorStateChanged

    private void minorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_minorStateChanged
        score.setMinorPenalies((Integer)minor.getValue());
    }//GEN-LAST:event_minorStateChanged

    public BlockPartyScore getScore() {
        return score;
    }

    public void setScore(BlockPartyScore score) {
        this.score = score;
        
        irPos.setSelectedItem(score.getIRgoal());
        
        auto1Block.setSelectedItem(score.getAutoGoal1());
        auto2Block.setSelectedItem(score.getAutoGoal2());
        auto1Pos.setSelectedItem(score.getAutoPos1());
        auto2Pos.setSelectedItem(score.getAutoPos2());
        
        pendulum1.setValue(score.getPendulum().getBasket1());
        pendulum2.setValue(score.getPendulum().getBasket2());
        pendulum3.setValue(score.getPendulum().getBasket3());        
        pendulum4.setValue(score.getPendulum().getBasket4());
        low.setValue(score.getPendulum().getLow());
        balanced.setSelected(score.getPendulum().isBalanced());
        
        flag.setSelectedItem(score.getFlagState());
        lift1.setSelected(score.isRobot1Lifted());
        lift2.setSelected(score.isRobot2Lifted());
        
        major.setValue(score.getMajorPenalties());
        minor.setValue(score.getMinorPenalies());
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel auto;
    private javax.swing.JComboBox auto1Block;
    private javax.swing.JComboBox auto1Pos;
    private javax.swing.JComboBox auto2Block;
    private javax.swing.JComboBox auto2Pos;
    private javax.swing.JCheckBox balanced;
    private javax.swing.JPanel blocks;
    private javax.swing.JPanel endgame;
    private javax.swing.JComboBox flag;
    private javax.swing.JComboBox irPos;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JCheckBox lift1;
    private javax.swing.JCheckBox lift2;
    private javax.swing.JSpinner low;
    private javax.swing.JSpinner major;
    private javax.swing.JSpinner minor;
    private javax.swing.JPanel penalties;
    private javax.swing.JSpinner pendulum1;
    private javax.swing.JSpinner pendulum2;
    private javax.swing.JSpinner pendulum3;
    private javax.swing.JSpinner pendulum4;
    // End of variables declaration//GEN-END:variables
}
